/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TermsRouteImport } from './routes/terms'
import { Route as SupportRouteImport } from './routes/support'
import { Route as ShippingRouteImport } from './routes/shipping'
import { Route as ResourcesRouteImport } from './routes/resources'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as RegisterRouteImport } from './routes/register'
import { Route as RatesRouteImport } from './routes/rates'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as PickupRouteImport } from './routes/pickup'
import { Route as LoginRouteImport } from './routes/login'
import { Route as LocationsRouteImport } from './routes/locations'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as CustomsRouteImport } from './routes/customs'
import { Route as CourierRouteImport } from './routes/courier'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as BusinessRouteImport } from './routes/business'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as AccessibilityRouteImport } from './routes/accessibility'
import { Route as AboutRouteImport } from './routes/about'
import { Route as IndexRouteImport } from './routes/index'
import { Route as TrackingIndexRouteImport } from './routes/tracking.index'
import { Route as DashboardIndexRouteImport } from './routes/dashboard.index'
import { Route as AdminIndexRouteImport } from './routes/admin.index'
import { Route as TrackingTrackingIdRouteImport } from './routes/tracking.$trackingId'
import { Route as DashboardShipmentsRouteImport } from './routes/dashboard.shipments'
import { Route as DashboardSettingsRouteImport } from './routes/dashboard.settings'
import { Route as DashboardNotificationsRouteImport } from './routes/dashboard.notifications'
import { Route as DashboardInvoicesRouteImport } from './routes/dashboard.invoices'
import { Route as DashboardApiKeysRouteImport } from './routes/dashboard.api-keys'
import { Route as DashboardAddressBookRouteImport } from './routes/dashboard.address-book'
import { Route as AdminUsersRouteImport } from './routes/admin.users'
import { Route as AdminSupportRouteImport } from './routes/admin.support'
import { Route as AdminShipmentsRouteImport } from './routes/admin.shipments'
import { Route as AdminPickupsRouteImport } from './routes/admin.pickups'
import { Route as AdminPaymentsRouteImport } from './routes/admin.payments'
import { Route as AdminMapRouteImport } from './routes/admin.map'
import { Route as AdminInvoicesRouteImport } from './routes/admin.invoices'
import { Route as AdminBroadcastRouteImport } from './routes/admin.broadcast'
import { Route as ShippingCheckoutTransactionIdRouteImport } from './routes/shipping.checkout.$transactionId'
import { Route as DashboardNotificationsIdRouteImport } from './routes/dashboard.notifications.$id'
import { Route as DashboardInvoicesInvoiceIdRouteImport } from './routes/dashboard.invoices.$invoiceId'

const TermsRoute = TermsRouteImport.update({
  id: '/terms',
  path: '/terms',
  getParentRoute: () => rootRouteImport,
} as any)
const SupportRoute = SupportRouteImport.update({
  id: '/support',
  path: '/support',
  getParentRoute: () => rootRouteImport,
} as any)
const ShippingRoute = ShippingRouteImport.update({
  id: '/shipping',
  path: '/shipping',
  getParentRoute: () => rootRouteImport,
} as any)
const ResourcesRoute = ResourcesRouteImport.update({
  id: '/resources',
  path: '/resources',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const RegisterRoute = RegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => rootRouteImport,
} as any)
const RatesRoute = RatesRouteImport.update({
  id: '/rates',
  path: '/rates',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const PickupRoute = PickupRouteImport.update({
  id: '/pickup',
  path: '/pickup',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const LocationsRoute = LocationsRouteImport.update({
  id: '/locations',
  path: '/locations',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const CustomsRoute = CustomsRouteImport.update({
  id: '/customs',
  path: '/customs',
  getParentRoute: () => rootRouteImport,
} as any)
const CourierRoute = CourierRouteImport.update({
  id: '/courier',
  path: '/courier',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const BusinessRoute = BusinessRouteImport.update({
  id: '/business',
  path: '/business',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const AccessibilityRoute = AccessibilityRouteImport.update({
  id: '/accessibility',
  path: '/accessibility',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const TrackingIndexRoute = TrackingIndexRouteImport.update({
  id: '/tracking/',
  path: '/tracking/',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardIndexRoute = DashboardIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => DashboardRoute,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminRoute,
} as any)
const TrackingTrackingIdRoute = TrackingTrackingIdRouteImport.update({
  id: '/tracking/$trackingId',
  path: '/tracking/$trackingId',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardShipmentsRoute = DashboardShipmentsRouteImport.update({
  id: '/shipments',
  path: '/shipments',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardSettingsRoute = DashboardSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardNotificationsRoute = DashboardNotificationsRouteImport.update({
  id: '/notifications',
  path: '/notifications',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardInvoicesRoute = DashboardInvoicesRouteImport.update({
  id: '/invoices',
  path: '/invoices',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardApiKeysRoute = DashboardApiKeysRouteImport.update({
  id: '/api-keys',
  path: '/api-keys',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardAddressBookRoute = DashboardAddressBookRouteImport.update({
  id: '/address-book',
  path: '/address-book',
  getParentRoute: () => DashboardRoute,
} as any)
const AdminUsersRoute = AdminUsersRouteImport.update({
  id: '/users',
  path: '/users',
  getParentRoute: () => AdminRoute,
} as any)
const AdminSupportRoute = AdminSupportRouteImport.update({
  id: '/support',
  path: '/support',
  getParentRoute: () => AdminRoute,
} as any)
const AdminShipmentsRoute = AdminShipmentsRouteImport.update({
  id: '/shipments',
  path: '/shipments',
  getParentRoute: () => AdminRoute,
} as any)
const AdminPickupsRoute = AdminPickupsRouteImport.update({
  id: '/pickups',
  path: '/pickups',
  getParentRoute: () => AdminRoute,
} as any)
const AdminPaymentsRoute = AdminPaymentsRouteImport.update({
  id: '/payments',
  path: '/payments',
  getParentRoute: () => AdminRoute,
} as any)
const AdminMapRoute = AdminMapRouteImport.update({
  id: '/map',
  path: '/map',
  getParentRoute: () => AdminRoute,
} as any)
const AdminInvoicesRoute = AdminInvoicesRouteImport.update({
  id: '/invoices',
  path: '/invoices',
  getParentRoute: () => AdminRoute,
} as any)
const AdminBroadcastRoute = AdminBroadcastRouteImport.update({
  id: '/broadcast',
  path: '/broadcast',
  getParentRoute: () => AdminRoute,
} as any)
const ShippingCheckoutTransactionIdRoute =
  ShippingCheckoutTransactionIdRouteImport.update({
    id: '/checkout/$transactionId',
    path: '/checkout/$transactionId',
    getParentRoute: () => ShippingRoute,
  } as any)
const DashboardNotificationsIdRoute =
  DashboardNotificationsIdRouteImport.update({
    id: '/$id',
    path: '/$id',
    getParentRoute: () => DashboardNotificationsRoute,
  } as any)
const DashboardInvoicesInvoiceIdRoute =
  DashboardInvoicesInvoiceIdRouteImport.update({
    id: '/$invoiceId',
    path: '/$invoiceId',
    getParentRoute: () => DashboardInvoicesRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/accessibility': typeof AccessibilityRoute
  '/admin': typeof AdminRouteWithChildren
  '/business': typeof BusinessRoute
  '/contact': typeof ContactRoute
  '/courier': typeof CourierRoute
  '/customs': typeof CustomsRoute
  '/dashboard': typeof DashboardRouteWithChildren
  '/locations': typeof LocationsRoute
  '/login': typeof LoginRoute
  '/pickup': typeof PickupRoute
  '/privacy': typeof PrivacyRoute
  '/rates': typeof RatesRoute
  '/register': typeof RegisterRoute
  '/reset-password': typeof ResetPasswordRoute
  '/resources': typeof ResourcesRoute
  '/shipping': typeof ShippingRouteWithChildren
  '/support': typeof SupportRoute
  '/terms': typeof TermsRoute
  '/admin/broadcast': typeof AdminBroadcastRoute
  '/admin/invoices': typeof AdminInvoicesRoute
  '/admin/map': typeof AdminMapRoute
  '/admin/payments': typeof AdminPaymentsRoute
  '/admin/pickups': typeof AdminPickupsRoute
  '/admin/shipments': typeof AdminShipmentsRoute
  '/admin/support': typeof AdminSupportRoute
  '/admin/users': typeof AdminUsersRoute
  '/dashboard/address-book': typeof DashboardAddressBookRoute
  '/dashboard/api-keys': typeof DashboardApiKeysRoute
  '/dashboard/invoices': typeof DashboardInvoicesRouteWithChildren
  '/dashboard/notifications': typeof DashboardNotificationsRouteWithChildren
  '/dashboard/settings': typeof DashboardSettingsRoute
  '/dashboard/shipments': typeof DashboardShipmentsRoute
  '/tracking/$trackingId': typeof TrackingTrackingIdRoute
  '/admin/': typeof AdminIndexRoute
  '/dashboard/': typeof DashboardIndexRoute
  '/tracking/': typeof TrackingIndexRoute
  '/dashboard/invoices/$invoiceId': typeof DashboardInvoicesInvoiceIdRoute
  '/dashboard/notifications/$id': typeof DashboardNotificationsIdRoute
  '/shipping/checkout/$transactionId': typeof ShippingCheckoutTransactionIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/accessibility': typeof AccessibilityRoute
  '/business': typeof BusinessRoute
  '/contact': typeof ContactRoute
  '/courier': typeof CourierRoute
  '/customs': typeof CustomsRoute
  '/locations': typeof LocationsRoute
  '/login': typeof LoginRoute
  '/pickup': typeof PickupRoute
  '/privacy': typeof PrivacyRoute
  '/rates': typeof RatesRoute
  '/register': typeof RegisterRoute
  '/reset-password': typeof ResetPasswordRoute
  '/resources': typeof ResourcesRoute
  '/shipping': typeof ShippingRouteWithChildren
  '/support': typeof SupportRoute
  '/terms': typeof TermsRoute
  '/admin/broadcast': typeof AdminBroadcastRoute
  '/admin/invoices': typeof AdminInvoicesRoute
  '/admin/map': typeof AdminMapRoute
  '/admin/payments': typeof AdminPaymentsRoute
  '/admin/pickups': typeof AdminPickupsRoute
  '/admin/shipments': typeof AdminShipmentsRoute
  '/admin/support': typeof AdminSupportRoute
  '/admin/users': typeof AdminUsersRoute
  '/dashboard/address-book': typeof DashboardAddressBookRoute
  '/dashboard/api-keys': typeof DashboardApiKeysRoute
  '/dashboard/invoices': typeof DashboardInvoicesRouteWithChildren
  '/dashboard/notifications': typeof DashboardNotificationsRouteWithChildren
  '/dashboard/settings': typeof DashboardSettingsRoute
  '/dashboard/shipments': typeof DashboardShipmentsRoute
  '/tracking/$trackingId': typeof TrackingTrackingIdRoute
  '/admin': typeof AdminIndexRoute
  '/dashboard': typeof DashboardIndexRoute
  '/tracking': typeof TrackingIndexRoute
  '/dashboard/invoices/$invoiceId': typeof DashboardInvoicesInvoiceIdRoute
  '/dashboard/notifications/$id': typeof DashboardNotificationsIdRoute
  '/shipping/checkout/$transactionId': typeof ShippingCheckoutTransactionIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/accessibility': typeof AccessibilityRoute
  '/admin': typeof AdminRouteWithChildren
  '/business': typeof BusinessRoute
  '/contact': typeof ContactRoute
  '/courier': typeof CourierRoute
  '/customs': typeof CustomsRoute
  '/dashboard': typeof DashboardRouteWithChildren
  '/locations': typeof LocationsRoute
  '/login': typeof LoginRoute
  '/pickup': typeof PickupRoute
  '/privacy': typeof PrivacyRoute
  '/rates': typeof RatesRoute
  '/register': typeof RegisterRoute
  '/reset-password': typeof ResetPasswordRoute
  '/resources': typeof ResourcesRoute
  '/shipping': typeof ShippingRouteWithChildren
  '/support': typeof SupportRoute
  '/terms': typeof TermsRoute
  '/admin/broadcast': typeof AdminBroadcastRoute
  '/admin/invoices': typeof AdminInvoicesRoute
  '/admin/map': typeof AdminMapRoute
  '/admin/payments': typeof AdminPaymentsRoute
  '/admin/pickups': typeof AdminPickupsRoute
  '/admin/shipments': typeof AdminShipmentsRoute
  '/admin/support': typeof AdminSupportRoute
  '/admin/users': typeof AdminUsersRoute
  '/dashboard/address-book': typeof DashboardAddressBookRoute
  '/dashboard/api-keys': typeof DashboardApiKeysRoute
  '/dashboard/invoices': typeof DashboardInvoicesRouteWithChildren
  '/dashboard/notifications': typeof DashboardNotificationsRouteWithChildren
  '/dashboard/settings': typeof DashboardSettingsRoute
  '/dashboard/shipments': typeof DashboardShipmentsRoute
  '/tracking/$trackingId': typeof TrackingTrackingIdRoute
  '/admin/': typeof AdminIndexRoute
  '/dashboard/': typeof DashboardIndexRoute
  '/tracking/': typeof TrackingIndexRoute
  '/dashboard/invoices/$invoiceId': typeof DashboardInvoicesInvoiceIdRoute
  '/dashboard/notifications/$id': typeof DashboardNotificationsIdRoute
  '/shipping/checkout/$transactionId': typeof ShippingCheckoutTransactionIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/accessibility'
    | '/admin'
    | '/business'
    | '/contact'
    | '/courier'
    | '/customs'
    | '/dashboard'
    | '/locations'
    | '/login'
    | '/pickup'
    | '/privacy'
    | '/rates'
    | '/register'
    | '/reset-password'
    | '/resources'
    | '/shipping'
    | '/support'
    | '/terms'
    | '/admin/broadcast'
    | '/admin/invoices'
    | '/admin/map'
    | '/admin/payments'
    | '/admin/pickups'
    | '/admin/shipments'
    | '/admin/support'
    | '/admin/users'
    | '/dashboard/address-book'
    | '/dashboard/api-keys'
    | '/dashboard/invoices'
    | '/dashboard/notifications'
    | '/dashboard/settings'
    | '/dashboard/shipments'
    | '/tracking/$trackingId'
    | '/admin/'
    | '/dashboard/'
    | '/tracking/'
    | '/dashboard/invoices/$invoiceId'
    | '/dashboard/notifications/$id'
    | '/shipping/checkout/$transactionId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/accessibility'
    | '/business'
    | '/contact'
    | '/courier'
    | '/customs'
    | '/locations'
    | '/login'
    | '/pickup'
    | '/privacy'
    | '/rates'
    | '/register'
    | '/reset-password'
    | '/resources'
    | '/shipping'
    | '/support'
    | '/terms'
    | '/admin/broadcast'
    | '/admin/invoices'
    | '/admin/map'
    | '/admin/payments'
    | '/admin/pickups'
    | '/admin/shipments'
    | '/admin/support'
    | '/admin/users'
    | '/dashboard/address-book'
    | '/dashboard/api-keys'
    | '/dashboard/invoices'
    | '/dashboard/notifications'
    | '/dashboard/settings'
    | '/dashboard/shipments'
    | '/tracking/$trackingId'
    | '/admin'
    | '/dashboard'
    | '/tracking'
    | '/dashboard/invoices/$invoiceId'
    | '/dashboard/notifications/$id'
    | '/shipping/checkout/$transactionId'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/accessibility'
    | '/admin'
    | '/business'
    | '/contact'
    | '/courier'
    | '/customs'
    | '/dashboard'
    | '/locations'
    | '/login'
    | '/pickup'
    | '/privacy'
    | '/rates'
    | '/register'
    | '/reset-password'
    | '/resources'
    | '/shipping'
    | '/support'
    | '/terms'
    | '/admin/broadcast'
    | '/admin/invoices'
    | '/admin/map'
    | '/admin/payments'
    | '/admin/pickups'
    | '/admin/shipments'
    | '/admin/support'
    | '/admin/users'
    | '/dashboard/address-book'
    | '/dashboard/api-keys'
    | '/dashboard/invoices'
    | '/dashboard/notifications'
    | '/dashboard/settings'
    | '/dashboard/shipments'
    | '/tracking/$trackingId'
    | '/admin/'
    | '/dashboard/'
    | '/tracking/'
    | '/dashboard/invoices/$invoiceId'
    | '/dashboard/notifications/$id'
    | '/shipping/checkout/$transactionId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  AccessibilityRoute: typeof AccessibilityRoute
  AdminRoute: typeof AdminRouteWithChildren
  BusinessRoute: typeof BusinessRoute
  ContactRoute: typeof ContactRoute
  CourierRoute: typeof CourierRoute
  CustomsRoute: typeof CustomsRoute
  DashboardRoute: typeof DashboardRouteWithChildren
  LocationsRoute: typeof LocationsRoute
  LoginRoute: typeof LoginRoute
  PickupRoute: typeof PickupRoute
  PrivacyRoute: typeof PrivacyRoute
  RatesRoute: typeof RatesRoute
  RegisterRoute: typeof RegisterRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  ResourcesRoute: typeof ResourcesRoute
  ShippingRoute: typeof ShippingRouteWithChildren
  SupportRoute: typeof SupportRoute
  TermsRoute: typeof TermsRoute
  TrackingTrackingIdRoute: typeof TrackingTrackingIdRoute
  TrackingIndexRoute: typeof TrackingIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/terms': {
      id: '/terms'
      path: '/terms'
      fullPath: '/terms'
      preLoaderRoute: typeof TermsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/support': {
      id: '/support'
      path: '/support'
      fullPath: '/support'
      preLoaderRoute: typeof SupportRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/shipping': {
      id: '/shipping'
      path: '/shipping'
      fullPath: '/shipping'
      preLoaderRoute: typeof ShippingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/resources': {
      id: '/resources'
      path: '/resources'
      fullPath: '/resources'
      preLoaderRoute: typeof ResourcesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/register': {
      id: '/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof RegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/rates': {
      id: '/rates'
      path: '/rates'
      fullPath: '/rates'
      preLoaderRoute: typeof RatesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pickup': {
      id: '/pickup'
      path: '/pickup'
      fullPath: '/pickup'
      preLoaderRoute: typeof PickupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/locations': {
      id: '/locations'
      path: '/locations'
      fullPath: '/locations'
      preLoaderRoute: typeof LocationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/customs': {
      id: '/customs'
      path: '/customs'
      fullPath: '/customs'
      preLoaderRoute: typeof CustomsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/courier': {
      id: '/courier'
      path: '/courier'
      fullPath: '/courier'
      preLoaderRoute: typeof CourierRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/business': {
      id: '/business'
      path: '/business'
      fullPath: '/business'
      preLoaderRoute: typeof BusinessRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/accessibility': {
      id: '/accessibility'
      path: '/accessibility'
      fullPath: '/accessibility'
      preLoaderRoute: typeof AccessibilityRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tracking/': {
      id: '/tracking/'
      path: '/tracking'
      fullPath: '/tracking/'
      preLoaderRoute: typeof TrackingIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/': {
      id: '/dashboard/'
      path: '/'
      fullPath: '/dashboard/'
      preLoaderRoute: typeof DashboardIndexRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/admin/': {
      id: '/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/tracking/$trackingId': {
      id: '/tracking/$trackingId'
      path: '/tracking/$trackingId'
      fullPath: '/tracking/$trackingId'
      preLoaderRoute: typeof TrackingTrackingIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/shipments': {
      id: '/dashboard/shipments'
      path: '/shipments'
      fullPath: '/dashboard/shipments'
      preLoaderRoute: typeof DashboardShipmentsRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/settings': {
      id: '/dashboard/settings'
      path: '/settings'
      fullPath: '/dashboard/settings'
      preLoaderRoute: typeof DashboardSettingsRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/notifications': {
      id: '/dashboard/notifications'
      path: '/notifications'
      fullPath: '/dashboard/notifications'
      preLoaderRoute: typeof DashboardNotificationsRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/invoices': {
      id: '/dashboard/invoices'
      path: '/invoices'
      fullPath: '/dashboard/invoices'
      preLoaderRoute: typeof DashboardInvoicesRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/api-keys': {
      id: '/dashboard/api-keys'
      path: '/api-keys'
      fullPath: '/dashboard/api-keys'
      preLoaderRoute: typeof DashboardApiKeysRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/address-book': {
      id: '/dashboard/address-book'
      path: '/address-book'
      fullPath: '/dashboard/address-book'
      preLoaderRoute: typeof DashboardAddressBookRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/admin/users': {
      id: '/admin/users'
      path: '/users'
      fullPath: '/admin/users'
      preLoaderRoute: typeof AdminUsersRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/support': {
      id: '/admin/support'
      path: '/support'
      fullPath: '/admin/support'
      preLoaderRoute: typeof AdminSupportRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/shipments': {
      id: '/admin/shipments'
      path: '/shipments'
      fullPath: '/admin/shipments'
      preLoaderRoute: typeof AdminShipmentsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/pickups': {
      id: '/admin/pickups'
      path: '/pickups'
      fullPath: '/admin/pickups'
      preLoaderRoute: typeof AdminPickupsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/payments': {
      id: '/admin/payments'
      path: '/payments'
      fullPath: '/admin/payments'
      preLoaderRoute: typeof AdminPaymentsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/map': {
      id: '/admin/map'
      path: '/map'
      fullPath: '/admin/map'
      preLoaderRoute: typeof AdminMapRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/invoices': {
      id: '/admin/invoices'
      path: '/invoices'
      fullPath: '/admin/invoices'
      preLoaderRoute: typeof AdminInvoicesRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/broadcast': {
      id: '/admin/broadcast'
      path: '/broadcast'
      fullPath: '/admin/broadcast'
      preLoaderRoute: typeof AdminBroadcastRouteImport
      parentRoute: typeof AdminRoute
    }
    '/shipping/checkout/$transactionId': {
      id: '/shipping/checkout/$transactionId'
      path: '/checkout/$transactionId'
      fullPath: '/shipping/checkout/$transactionId'
      preLoaderRoute: typeof ShippingCheckoutTransactionIdRouteImport
      parentRoute: typeof ShippingRoute
    }
    '/dashboard/notifications/$id': {
      id: '/dashboard/notifications/$id'
      path: '/$id'
      fullPath: '/dashboard/notifications/$id'
      preLoaderRoute: typeof DashboardNotificationsIdRouteImport
      parentRoute: typeof DashboardNotificationsRoute
    }
    '/dashboard/invoices/$invoiceId': {
      id: '/dashboard/invoices/$invoiceId'
      path: '/$invoiceId'
      fullPath: '/dashboard/invoices/$invoiceId'
      preLoaderRoute: typeof DashboardInvoicesInvoiceIdRouteImport
      parentRoute: typeof DashboardInvoicesRoute
    }
  }
}

interface AdminRouteChildren {
  AdminBroadcastRoute: typeof AdminBroadcastRoute
  AdminInvoicesRoute: typeof AdminInvoicesRoute
  AdminMapRoute: typeof AdminMapRoute
  AdminPaymentsRoute: typeof AdminPaymentsRoute
  AdminPickupsRoute: typeof AdminPickupsRoute
  AdminShipmentsRoute: typeof AdminShipmentsRoute
  AdminSupportRoute: typeof AdminSupportRoute
  AdminUsersRoute: typeof AdminUsersRoute
  AdminIndexRoute: typeof AdminIndexRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminBroadcastRoute: AdminBroadcastRoute,
  AdminInvoicesRoute: AdminInvoicesRoute,
  AdminMapRoute: AdminMapRoute,
  AdminPaymentsRoute: AdminPaymentsRoute,
  AdminPickupsRoute: AdminPickupsRoute,
  AdminShipmentsRoute: AdminShipmentsRoute,
  AdminSupportRoute: AdminSupportRoute,
  AdminUsersRoute: AdminUsersRoute,
  AdminIndexRoute: AdminIndexRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

interface DashboardInvoicesRouteChildren {
  DashboardInvoicesInvoiceIdRoute: typeof DashboardInvoicesInvoiceIdRoute
}

const DashboardInvoicesRouteChildren: DashboardInvoicesRouteChildren = {
  DashboardInvoicesInvoiceIdRoute: DashboardInvoicesInvoiceIdRoute,
}

const DashboardInvoicesRouteWithChildren =
  DashboardInvoicesRoute._addFileChildren(DashboardInvoicesRouteChildren)

interface DashboardNotificationsRouteChildren {
  DashboardNotificationsIdRoute: typeof DashboardNotificationsIdRoute
}

const DashboardNotificationsRouteChildren: DashboardNotificationsRouteChildren =
  {
    DashboardNotificationsIdRoute: DashboardNotificationsIdRoute,
  }

const DashboardNotificationsRouteWithChildren =
  DashboardNotificationsRoute._addFileChildren(
    DashboardNotificationsRouteChildren,
  )

interface DashboardRouteChildren {
  DashboardAddressBookRoute: typeof DashboardAddressBookRoute
  DashboardApiKeysRoute: typeof DashboardApiKeysRoute
  DashboardInvoicesRoute: typeof DashboardInvoicesRouteWithChildren
  DashboardNotificationsRoute: typeof DashboardNotificationsRouteWithChildren
  DashboardSettingsRoute: typeof DashboardSettingsRoute
  DashboardShipmentsRoute: typeof DashboardShipmentsRoute
  DashboardIndexRoute: typeof DashboardIndexRoute
}

const DashboardRouteChildren: DashboardRouteChildren = {
  DashboardAddressBookRoute: DashboardAddressBookRoute,
  DashboardApiKeysRoute: DashboardApiKeysRoute,
  DashboardInvoicesRoute: DashboardInvoicesRouteWithChildren,
  DashboardNotificationsRoute: DashboardNotificationsRouteWithChildren,
  DashboardSettingsRoute: DashboardSettingsRoute,
  DashboardShipmentsRoute: DashboardShipmentsRoute,
  DashboardIndexRoute: DashboardIndexRoute,
}

const DashboardRouteWithChildren = DashboardRoute._addFileChildren(
  DashboardRouteChildren,
)

interface ShippingRouteChildren {
  ShippingCheckoutTransactionIdRoute: typeof ShippingCheckoutTransactionIdRoute
}

const ShippingRouteChildren: ShippingRouteChildren = {
  ShippingCheckoutTransactionIdRoute: ShippingCheckoutTransactionIdRoute,
}

const ShippingRouteWithChildren = ShippingRoute._addFileChildren(
  ShippingRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  AccessibilityRoute: AccessibilityRoute,
  AdminRoute: AdminRouteWithChildren,
  BusinessRoute: BusinessRoute,
  ContactRoute: ContactRoute,
  CourierRoute: CourierRoute,
  CustomsRoute: CustomsRoute,
  DashboardRoute: DashboardRouteWithChildren,
  LocationsRoute: LocationsRoute,
  LoginRoute: LoginRoute,
  PickupRoute: PickupRoute,
  PrivacyRoute: PrivacyRoute,
  RatesRoute: RatesRoute,
  RegisterRoute: RegisterRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  ResourcesRoute: ResourcesRoute,
  ShippingRoute: ShippingRouteWithChildren,
  SupportRoute: SupportRoute,
  TermsRoute: TermsRoute,
  TrackingTrackingIdRoute: TrackingTrackingIdRoute,
  TrackingIndexRoute: TrackingIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
