/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TermsRouteImport } from './routes/terms'
import { Route as SupportRouteImport } from './routes/support'
import { Route as ShippingRouteImport } from './routes/shipping'
import { Route as ResourcesRouteImport } from './routes/resources'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as RegisterRouteImport } from './routes/register'
import { Route as RatesRouteImport } from './routes/rates'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as PickupRouteImport } from './routes/pickup'
import { Route as LoginRouteImport } from './routes/login'
import { Route as LocationsRouteImport } from './routes/locations'
import { Route as CustomsRouteImport } from './routes/customs'
import { Route as CourierRouteImport } from './routes/courier'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as BusinessRouteImport } from './routes/business'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as AboutRouteImport } from './routes/about'
import { Route as IndexRouteImport } from './routes/index'
import { Route as TrackingIndexRouteImport } from './routes/tracking.index'
import { Route as AdminIndexRouteImport } from './routes/admin.index'
import { Route as TrackingTrackingIdRouteImport } from './routes/tracking.$trackingId'
import { Route as ResourcesSlugRouteImport } from './routes/resources.$slug'
import { Route as PayCaseIdRouteImport } from './routes/pay.$caseId'
import { Route as InvoiceTrackingIdRouteImport } from './routes/invoice.$trackingId'
import { Route as AdminUsersRouteImport } from './routes/admin.users'
import { Route as AdminSupportRouteImport } from './routes/admin.support'
import { Route as AdminShipmentsRouteImport } from './routes/admin.shipments'
import { Route as AdminSettingsRouteImport } from './routes/admin.settings'
import { Route as AdminReportsRouteImport } from './routes/admin.reports'
import { Route as AdminPricingRouteImport } from './routes/admin.pricing'
import { Route as AdminPickupsRouteImport } from './routes/admin.pickups'
import { Route as AdminPaymentsConfigRouteImport } from './routes/admin.payments-config'
import { Route as AdminPaymentsRouteImport } from './routes/admin.payments'
import { Route as AdminOrdersRouteImport } from './routes/admin.orders'
import { Route as AdminMapRouteImport } from './routes/admin.map'
import { Route as AdminInvoicesRouteImport } from './routes/admin.invoices'
import { Route as AdminFleetRouteImport } from './routes/admin.fleet'
import { Route as AdminDriversRouteImport } from './routes/admin.drivers'
import { Route as AdminCmsRouteImport } from './routes/admin.cms'
import { Route as AdminClearanceRouteImport } from './routes/admin.clearance'
import { Route as AdminBroadcastRouteImport } from './routes/admin.broadcast'
import { Route as AdminAuditLogsRouteImport } from './routes/admin.audit-logs'
import { Route as AdminAnalyticsRouteImport } from './routes/admin.analytics'
import { Route as AdminShipmentsCreateRouteImport } from './routes/admin.shipments_.create'

const TermsRoute = TermsRouteImport.update({
  id: '/terms',
  path: '/terms',
  getParentRoute: () => rootRouteImport,
} as any)
const SupportRoute = SupportRouteImport.update({
  id: '/support',
  path: '/support',
  getParentRoute: () => rootRouteImport,
} as any)
const ShippingRoute = ShippingRouteImport.update({
  id: '/shipping',
  path: '/shipping',
  getParentRoute: () => rootRouteImport,
} as any)
const ResourcesRoute = ResourcesRouteImport.update({
  id: '/resources',
  path: '/resources',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const RegisterRoute = RegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => rootRouteImport,
} as any)
const RatesRoute = RatesRouteImport.update({
  id: '/rates',
  path: '/rates',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const PickupRoute = PickupRouteImport.update({
  id: '/pickup',
  path: '/pickup',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const LocationsRoute = LocationsRouteImport.update({
  id: '/locations',
  path: '/locations',
  getParentRoute: () => rootRouteImport,
} as any)
const CustomsRoute = CustomsRouteImport.update({
  id: '/customs',
  path: '/customs',
  getParentRoute: () => rootRouteImport,
} as any)
const CourierRoute = CourierRouteImport.update({
  id: '/courier',
  path: '/courier',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const BusinessRoute = BusinessRouteImport.update({
  id: '/business',
  path: '/business',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const TrackingIndexRoute = TrackingIndexRouteImport.update({
  id: '/tracking/',
  path: '/tracking/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminRoute,
} as any)
const TrackingTrackingIdRoute = TrackingTrackingIdRouteImport.update({
  id: '/tracking/$trackingId',
  path: '/tracking/$trackingId',
  getParentRoute: () => rootRouteImport,
} as any)
const ResourcesSlugRoute = ResourcesSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => ResourcesRoute,
} as any)
const PayCaseIdRoute = PayCaseIdRouteImport.update({
  id: '/pay/$caseId',
  path: '/pay/$caseId',
  getParentRoute: () => rootRouteImport,
} as any)
const InvoiceTrackingIdRoute = InvoiceTrackingIdRouteImport.update({
  id: '/invoice/$trackingId',
  path: '/invoice/$trackingId',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminUsersRoute = AdminUsersRouteImport.update({
  id: '/users',
  path: '/users',
  getParentRoute: () => AdminRoute,
} as any)
const AdminSupportRoute = AdminSupportRouteImport.update({
  id: '/support',
  path: '/support',
  getParentRoute: () => AdminRoute,
} as any)
const AdminShipmentsRoute = AdminShipmentsRouteImport.update({
  id: '/shipments',
  path: '/shipments',
  getParentRoute: () => AdminRoute,
} as any)
const AdminSettingsRoute = AdminSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AdminRoute,
} as any)
const AdminReportsRoute = AdminReportsRouteImport.update({
  id: '/reports',
  path: '/reports',
  getParentRoute: () => AdminRoute,
} as any)
const AdminPricingRoute = AdminPricingRouteImport.update({
  id: '/pricing',
  path: '/pricing',
  getParentRoute: () => AdminRoute,
} as any)
const AdminPickupsRoute = AdminPickupsRouteImport.update({
  id: '/pickups',
  path: '/pickups',
  getParentRoute: () => AdminRoute,
} as any)
const AdminPaymentsConfigRoute = AdminPaymentsConfigRouteImport.update({
  id: '/payments-config',
  path: '/payments-config',
  getParentRoute: () => AdminRoute,
} as any)
const AdminPaymentsRoute = AdminPaymentsRouteImport.update({
  id: '/payments',
  path: '/payments',
  getParentRoute: () => AdminRoute,
} as any)
const AdminOrdersRoute = AdminOrdersRouteImport.update({
  id: '/orders',
  path: '/orders',
  getParentRoute: () => AdminRoute,
} as any)
const AdminMapRoute = AdminMapRouteImport.update({
  id: '/map',
  path: '/map',
  getParentRoute: () => AdminRoute,
} as any)
const AdminInvoicesRoute = AdminInvoicesRouteImport.update({
  id: '/invoices',
  path: '/invoices',
  getParentRoute: () => AdminRoute,
} as any)
const AdminFleetRoute = AdminFleetRouteImport.update({
  id: '/fleet',
  path: '/fleet',
  getParentRoute: () => AdminRoute,
} as any)
const AdminDriversRoute = AdminDriversRouteImport.update({
  id: '/drivers',
  path: '/drivers',
  getParentRoute: () => AdminRoute,
} as any)
const AdminCmsRoute = AdminCmsRouteImport.update({
  id: '/cms',
  path: '/cms',
  getParentRoute: () => AdminRoute,
} as any)
const AdminClearanceRoute = AdminClearanceRouteImport.update({
  id: '/clearance',
  path: '/clearance',
  getParentRoute: () => AdminRoute,
} as any)
const AdminBroadcastRoute = AdminBroadcastRouteImport.update({
  id: '/broadcast',
  path: '/broadcast',
  getParentRoute: () => AdminRoute,
} as any)
const AdminAuditLogsRoute = AdminAuditLogsRouteImport.update({
  id: '/audit-logs',
  path: '/audit-logs',
  getParentRoute: () => AdminRoute,
} as any)
const AdminAnalyticsRoute = AdminAnalyticsRouteImport.update({
  id: '/analytics',
  path: '/analytics',
  getParentRoute: () => AdminRoute,
} as any)
const AdminShipmentsCreateRoute = AdminShipmentsCreateRouteImport.update({
  id: '/shipments_/create',
  path: '/shipments/create',
  getParentRoute: () => AdminRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/admin': typeof AdminRouteWithChildren
  '/business': typeof BusinessRoute
  '/contact': typeof ContactRoute
  '/courier': typeof CourierRoute
  '/customs': typeof CustomsRoute
  '/locations': typeof LocationsRoute
  '/login': typeof LoginRoute
  '/pickup': typeof PickupRoute
  '/privacy': typeof PrivacyRoute
  '/rates': typeof RatesRoute
  '/register': typeof RegisterRoute
  '/reset-password': typeof ResetPasswordRoute
  '/resources': typeof ResourcesRouteWithChildren
  '/shipping': typeof ShippingRoute
  '/support': typeof SupportRoute
  '/terms': typeof TermsRoute
  '/admin/analytics': typeof AdminAnalyticsRoute
  '/admin/audit-logs': typeof AdminAuditLogsRoute
  '/admin/broadcast': typeof AdminBroadcastRoute
  '/admin/clearance': typeof AdminClearanceRoute
  '/admin/cms': typeof AdminCmsRoute
  '/admin/drivers': typeof AdminDriversRoute
  '/admin/fleet': typeof AdminFleetRoute
  '/admin/invoices': typeof AdminInvoicesRoute
  '/admin/map': typeof AdminMapRoute
  '/admin/orders': typeof AdminOrdersRoute
  '/admin/payments': typeof AdminPaymentsRoute
  '/admin/payments-config': typeof AdminPaymentsConfigRoute
  '/admin/pickups': typeof AdminPickupsRoute
  '/admin/pricing': typeof AdminPricingRoute
  '/admin/reports': typeof AdminReportsRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/admin/shipments': typeof AdminShipmentsRoute
  '/admin/support': typeof AdminSupportRoute
  '/admin/users': typeof AdminUsersRoute
  '/invoice/$trackingId': typeof InvoiceTrackingIdRoute
  '/pay/$caseId': typeof PayCaseIdRoute
  '/resources/$slug': typeof ResourcesSlugRoute
  '/tracking/$trackingId': typeof TrackingTrackingIdRoute
  '/admin/': typeof AdminIndexRoute
  '/tracking/': typeof TrackingIndexRoute
  '/admin/shipments/create': typeof AdminShipmentsCreateRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/business': typeof BusinessRoute
  '/contact': typeof ContactRoute
  '/courier': typeof CourierRoute
  '/customs': typeof CustomsRoute
  '/locations': typeof LocationsRoute
  '/login': typeof LoginRoute
  '/pickup': typeof PickupRoute
  '/privacy': typeof PrivacyRoute
  '/rates': typeof RatesRoute
  '/register': typeof RegisterRoute
  '/reset-password': typeof ResetPasswordRoute
  '/resources': typeof ResourcesRouteWithChildren
  '/shipping': typeof ShippingRoute
  '/support': typeof SupportRoute
  '/terms': typeof TermsRoute
  '/admin/analytics': typeof AdminAnalyticsRoute
  '/admin/audit-logs': typeof AdminAuditLogsRoute
  '/admin/broadcast': typeof AdminBroadcastRoute
  '/admin/clearance': typeof AdminClearanceRoute
  '/admin/cms': typeof AdminCmsRoute
  '/admin/drivers': typeof AdminDriversRoute
  '/admin/fleet': typeof AdminFleetRoute
  '/admin/invoices': typeof AdminInvoicesRoute
  '/admin/map': typeof AdminMapRoute
  '/admin/orders': typeof AdminOrdersRoute
  '/admin/payments': typeof AdminPaymentsRoute
  '/admin/payments-config': typeof AdminPaymentsConfigRoute
  '/admin/pickups': typeof AdminPickupsRoute
  '/admin/pricing': typeof AdminPricingRoute
  '/admin/reports': typeof AdminReportsRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/admin/shipments': typeof AdminShipmentsRoute
  '/admin/support': typeof AdminSupportRoute
  '/admin/users': typeof AdminUsersRoute
  '/invoice/$trackingId': typeof InvoiceTrackingIdRoute
  '/pay/$caseId': typeof PayCaseIdRoute
  '/resources/$slug': typeof ResourcesSlugRoute
  '/tracking/$trackingId': typeof TrackingTrackingIdRoute
  '/admin': typeof AdminIndexRoute
  '/tracking': typeof TrackingIndexRoute
  '/admin/shipments/create': typeof AdminShipmentsCreateRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/admin': typeof AdminRouteWithChildren
  '/business': typeof BusinessRoute
  '/contact': typeof ContactRoute
  '/courier': typeof CourierRoute
  '/customs': typeof CustomsRoute
  '/locations': typeof LocationsRoute
  '/login': typeof LoginRoute
  '/pickup': typeof PickupRoute
  '/privacy': typeof PrivacyRoute
  '/rates': typeof RatesRoute
  '/register': typeof RegisterRoute
  '/reset-password': typeof ResetPasswordRoute
  '/resources': typeof ResourcesRouteWithChildren
  '/shipping': typeof ShippingRoute
  '/support': typeof SupportRoute
  '/terms': typeof TermsRoute
  '/admin/analytics': typeof AdminAnalyticsRoute
  '/admin/audit-logs': typeof AdminAuditLogsRoute
  '/admin/broadcast': typeof AdminBroadcastRoute
  '/admin/clearance': typeof AdminClearanceRoute
  '/admin/cms': typeof AdminCmsRoute
  '/admin/drivers': typeof AdminDriversRoute
  '/admin/fleet': typeof AdminFleetRoute
  '/admin/invoices': typeof AdminInvoicesRoute
  '/admin/map': typeof AdminMapRoute
  '/admin/orders': typeof AdminOrdersRoute
  '/admin/payments': typeof AdminPaymentsRoute
  '/admin/payments-config': typeof AdminPaymentsConfigRoute
  '/admin/pickups': typeof AdminPickupsRoute
  '/admin/pricing': typeof AdminPricingRoute
  '/admin/reports': typeof AdminReportsRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/admin/shipments': typeof AdminShipmentsRoute
  '/admin/support': typeof AdminSupportRoute
  '/admin/users': typeof AdminUsersRoute
  '/invoice/$trackingId': typeof InvoiceTrackingIdRoute
  '/pay/$caseId': typeof PayCaseIdRoute
  '/resources/$slug': typeof ResourcesSlugRoute
  '/tracking/$trackingId': typeof TrackingTrackingIdRoute
  '/admin/': typeof AdminIndexRoute
  '/tracking/': typeof TrackingIndexRoute
  '/admin/shipments_/create': typeof AdminShipmentsCreateRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/admin'
    | '/business'
    | '/contact'
    | '/courier'
    | '/customs'
    | '/locations'
    | '/login'
    | '/pickup'
    | '/privacy'
    | '/rates'
    | '/register'
    | '/reset-password'
    | '/resources'
    | '/shipping'
    | '/support'
    | '/terms'
    | '/admin/analytics'
    | '/admin/audit-logs'
    | '/admin/broadcast'
    | '/admin/clearance'
    | '/admin/cms'
    | '/admin/drivers'
    | '/admin/fleet'
    | '/admin/invoices'
    | '/admin/map'
    | '/admin/orders'
    | '/admin/payments'
    | '/admin/payments-config'
    | '/admin/pickups'
    | '/admin/pricing'
    | '/admin/reports'
    | '/admin/settings'
    | '/admin/shipments'
    | '/admin/support'
    | '/admin/users'
    | '/invoice/$trackingId'
    | '/pay/$caseId'
    | '/resources/$slug'
    | '/tracking/$trackingId'
    | '/admin/'
    | '/tracking/'
    | '/admin/shipments/create'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/business'
    | '/contact'
    | '/courier'
    | '/customs'
    | '/locations'
    | '/login'
    | '/pickup'
    | '/privacy'
    | '/rates'
    | '/register'
    | '/reset-password'
    | '/resources'
    | '/shipping'
    | '/support'
    | '/terms'
    | '/admin/analytics'
    | '/admin/audit-logs'
    | '/admin/broadcast'
    | '/admin/clearance'
    | '/admin/cms'
    | '/admin/drivers'
    | '/admin/fleet'
    | '/admin/invoices'
    | '/admin/map'
    | '/admin/orders'
    | '/admin/payments'
    | '/admin/payments-config'
    | '/admin/pickups'
    | '/admin/pricing'
    | '/admin/reports'
    | '/admin/settings'
    | '/admin/shipments'
    | '/admin/support'
    | '/admin/users'
    | '/invoice/$trackingId'
    | '/pay/$caseId'
    | '/resources/$slug'
    | '/tracking/$trackingId'
    | '/admin'
    | '/tracking'
    | '/admin/shipments/create'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/admin'
    | '/business'
    | '/contact'
    | '/courier'
    | '/customs'
    | '/locations'
    | '/login'
    | '/pickup'
    | '/privacy'
    | '/rates'
    | '/register'
    | '/reset-password'
    | '/resources'
    | '/shipping'
    | '/support'
    | '/terms'
    | '/admin/analytics'
    | '/admin/audit-logs'
    | '/admin/broadcast'
    | '/admin/clearance'
    | '/admin/cms'
    | '/admin/drivers'
    | '/admin/fleet'
    | '/admin/invoices'
    | '/admin/map'
    | '/admin/orders'
    | '/admin/payments'
    | '/admin/payments-config'
    | '/admin/pickups'
    | '/admin/pricing'
    | '/admin/reports'
    | '/admin/settings'
    | '/admin/shipments'
    | '/admin/support'
    | '/admin/users'
    | '/invoice/$trackingId'
    | '/pay/$caseId'
    | '/resources/$slug'
    | '/tracking/$trackingId'
    | '/admin/'
    | '/tracking/'
    | '/admin/shipments_/create'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  AdminRoute: typeof AdminRouteWithChildren
  BusinessRoute: typeof BusinessRoute
  ContactRoute: typeof ContactRoute
  CourierRoute: typeof CourierRoute
  CustomsRoute: typeof CustomsRoute
  LocationsRoute: typeof LocationsRoute
  LoginRoute: typeof LoginRoute
  PickupRoute: typeof PickupRoute
  PrivacyRoute: typeof PrivacyRoute
  RatesRoute: typeof RatesRoute
  RegisterRoute: typeof RegisterRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  ResourcesRoute: typeof ResourcesRouteWithChildren
  ShippingRoute: typeof ShippingRoute
  SupportRoute: typeof SupportRoute
  TermsRoute: typeof TermsRoute
  InvoiceTrackingIdRoute: typeof InvoiceTrackingIdRoute
  PayCaseIdRoute: typeof PayCaseIdRoute
  TrackingTrackingIdRoute: typeof TrackingTrackingIdRoute
  TrackingIndexRoute: typeof TrackingIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/terms': {
      id: '/terms'
      path: '/terms'
      fullPath: '/terms'
      preLoaderRoute: typeof TermsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/support': {
      id: '/support'
      path: '/support'
      fullPath: '/support'
      preLoaderRoute: typeof SupportRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/shipping': {
      id: '/shipping'
      path: '/shipping'
      fullPath: '/shipping'
      preLoaderRoute: typeof ShippingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/resources': {
      id: '/resources'
      path: '/resources'
      fullPath: '/resources'
      preLoaderRoute: typeof ResourcesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/register': {
      id: '/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof RegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/rates': {
      id: '/rates'
      path: '/rates'
      fullPath: '/rates'
      preLoaderRoute: typeof RatesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pickup': {
      id: '/pickup'
      path: '/pickup'
      fullPath: '/pickup'
      preLoaderRoute: typeof PickupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/locations': {
      id: '/locations'
      path: '/locations'
      fullPath: '/locations'
      preLoaderRoute: typeof LocationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/customs': {
      id: '/customs'
      path: '/customs'
      fullPath: '/customs'
      preLoaderRoute: typeof CustomsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/courier': {
      id: '/courier'
      path: '/courier'
      fullPath: '/courier'
      preLoaderRoute: typeof CourierRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/business': {
      id: '/business'
      path: '/business'
      fullPath: '/business'
      preLoaderRoute: typeof BusinessRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tracking/': {
      id: '/tracking/'
      path: '/tracking'
      fullPath: '/tracking/'
      preLoaderRoute: typeof TrackingIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/tracking/$trackingId': {
      id: '/tracking/$trackingId'
      path: '/tracking/$trackingId'
      fullPath: '/tracking/$trackingId'
      preLoaderRoute: typeof TrackingTrackingIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/resources/$slug': {
      id: '/resources/$slug'
      path: '/$slug'
      fullPath: '/resources/$slug'
      preLoaderRoute: typeof ResourcesSlugRouteImport
      parentRoute: typeof ResourcesRoute
    }
    '/pay/$caseId': {
      id: '/pay/$caseId'
      path: '/pay/$caseId'
      fullPath: '/pay/$caseId'
      preLoaderRoute: typeof PayCaseIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/invoice/$trackingId': {
      id: '/invoice/$trackingId'
      path: '/invoice/$trackingId'
      fullPath: '/invoice/$trackingId'
      preLoaderRoute: typeof InvoiceTrackingIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/users': {
      id: '/admin/users'
      path: '/users'
      fullPath: '/admin/users'
      preLoaderRoute: typeof AdminUsersRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/support': {
      id: '/admin/support'
      path: '/support'
      fullPath: '/admin/support'
      preLoaderRoute: typeof AdminSupportRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/shipments': {
      id: '/admin/shipments'
      path: '/shipments'
      fullPath: '/admin/shipments'
      preLoaderRoute: typeof AdminShipmentsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/settings': {
      id: '/admin/settings'
      path: '/settings'
      fullPath: '/admin/settings'
      preLoaderRoute: typeof AdminSettingsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/reports': {
      id: '/admin/reports'
      path: '/reports'
      fullPath: '/admin/reports'
      preLoaderRoute: typeof AdminReportsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/pricing': {
      id: '/admin/pricing'
      path: '/pricing'
      fullPath: '/admin/pricing'
      preLoaderRoute: typeof AdminPricingRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/pickups': {
      id: '/admin/pickups'
      path: '/pickups'
      fullPath: '/admin/pickups'
      preLoaderRoute: typeof AdminPickupsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/payments-config': {
      id: '/admin/payments-config'
      path: '/payments-config'
      fullPath: '/admin/payments-config'
      preLoaderRoute: typeof AdminPaymentsConfigRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/payments': {
      id: '/admin/payments'
      path: '/payments'
      fullPath: '/admin/payments'
      preLoaderRoute: typeof AdminPaymentsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/orders': {
      id: '/admin/orders'
      path: '/orders'
      fullPath: '/admin/orders'
      preLoaderRoute: typeof AdminOrdersRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/map': {
      id: '/admin/map'
      path: '/map'
      fullPath: '/admin/map'
      preLoaderRoute: typeof AdminMapRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/invoices': {
      id: '/admin/invoices'
      path: '/invoices'
      fullPath: '/admin/invoices'
      preLoaderRoute: typeof AdminInvoicesRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/fleet': {
      id: '/admin/fleet'
      path: '/fleet'
      fullPath: '/admin/fleet'
      preLoaderRoute: typeof AdminFleetRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/drivers': {
      id: '/admin/drivers'
      path: '/drivers'
      fullPath: '/admin/drivers'
      preLoaderRoute: typeof AdminDriversRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/cms': {
      id: '/admin/cms'
      path: '/cms'
      fullPath: '/admin/cms'
      preLoaderRoute: typeof AdminCmsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/clearance': {
      id: '/admin/clearance'
      path: '/clearance'
      fullPath: '/admin/clearance'
      preLoaderRoute: typeof AdminClearanceRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/broadcast': {
      id: '/admin/broadcast'
      path: '/broadcast'
      fullPath: '/admin/broadcast'
      preLoaderRoute: typeof AdminBroadcastRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/audit-logs': {
      id: '/admin/audit-logs'
      path: '/audit-logs'
      fullPath: '/admin/audit-logs'
      preLoaderRoute: typeof AdminAuditLogsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/analytics': {
      id: '/admin/analytics'
      path: '/analytics'
      fullPath: '/admin/analytics'
      preLoaderRoute: typeof AdminAnalyticsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/shipments_/create': {
      id: '/admin/shipments_/create'
      path: '/shipments/create'
      fullPath: '/admin/shipments/create'
      preLoaderRoute: typeof AdminShipmentsCreateRouteImport
      parentRoute: typeof AdminRoute
    }
  }
}

interface AdminRouteChildren {
  AdminAnalyticsRoute: typeof AdminAnalyticsRoute
  AdminAuditLogsRoute: typeof AdminAuditLogsRoute
  AdminBroadcastRoute: typeof AdminBroadcastRoute
  AdminClearanceRoute: typeof AdminClearanceRoute
  AdminCmsRoute: typeof AdminCmsRoute
  AdminDriversRoute: typeof AdminDriversRoute
  AdminFleetRoute: typeof AdminFleetRoute
  AdminInvoicesRoute: typeof AdminInvoicesRoute
  AdminMapRoute: typeof AdminMapRoute
  AdminOrdersRoute: typeof AdminOrdersRoute
  AdminPaymentsRoute: typeof AdminPaymentsRoute
  AdminPaymentsConfigRoute: typeof AdminPaymentsConfigRoute
  AdminPickupsRoute: typeof AdminPickupsRoute
  AdminPricingRoute: typeof AdminPricingRoute
  AdminReportsRoute: typeof AdminReportsRoute
  AdminSettingsRoute: typeof AdminSettingsRoute
  AdminShipmentsRoute: typeof AdminShipmentsRoute
  AdminSupportRoute: typeof AdminSupportRoute
  AdminUsersRoute: typeof AdminUsersRoute
  AdminIndexRoute: typeof AdminIndexRoute
  AdminShipmentsCreateRoute: typeof AdminShipmentsCreateRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminAnalyticsRoute: AdminAnalyticsRoute,
  AdminAuditLogsRoute: AdminAuditLogsRoute,
  AdminBroadcastRoute: AdminBroadcastRoute,
  AdminClearanceRoute: AdminClearanceRoute,
  AdminCmsRoute: AdminCmsRoute,
  AdminDriversRoute: AdminDriversRoute,
  AdminFleetRoute: AdminFleetRoute,
  AdminInvoicesRoute: AdminInvoicesRoute,
  AdminMapRoute: AdminMapRoute,
  AdminOrdersRoute: AdminOrdersRoute,
  AdminPaymentsRoute: AdminPaymentsRoute,
  AdminPaymentsConfigRoute: AdminPaymentsConfigRoute,
  AdminPickupsRoute: AdminPickupsRoute,
  AdminPricingRoute: AdminPricingRoute,
  AdminReportsRoute: AdminReportsRoute,
  AdminSettingsRoute: AdminSettingsRoute,
  AdminShipmentsRoute: AdminShipmentsRoute,
  AdminSupportRoute: AdminSupportRoute,
  AdminUsersRoute: AdminUsersRoute,
  AdminIndexRoute: AdminIndexRoute,
  AdminShipmentsCreateRoute: AdminShipmentsCreateRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

interface ResourcesRouteChildren {
  ResourcesSlugRoute: typeof ResourcesSlugRoute
}

const ResourcesRouteChildren: ResourcesRouteChildren = {
  ResourcesSlugRoute: ResourcesSlugRoute,
}

const ResourcesRouteWithChildren = ResourcesRoute._addFileChildren(
  ResourcesRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  AdminRoute: AdminRouteWithChildren,
  BusinessRoute: BusinessRoute,
  ContactRoute: ContactRoute,
  CourierRoute: CourierRoute,
  CustomsRoute: CustomsRoute,
  LocationsRoute: LocationsRoute,
  LoginRoute: LoginRoute,
  PickupRoute: PickupRoute,
  PrivacyRoute: PrivacyRoute,
  RatesRoute: RatesRoute,
  RegisterRoute: RegisterRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  ResourcesRoute: ResourcesRouteWithChildren,
  ShippingRoute: ShippingRoute,
  SupportRoute: SupportRoute,
  TermsRoute: TermsRoute,
  InvoiceTrackingIdRoute: InvoiceTrackingIdRoute,
  PayCaseIdRoute: PayCaseIdRoute,
  TrackingTrackingIdRoute: TrackingTrackingIdRoute,
  TrackingIndexRoute: TrackingIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
